"""Remove circular dependency in bills-bill_cancellations

Revision ID: 6878dfe2df4a
Revises: 6d2b590a4a1f
Create Date: 2023-05-08 13:36:24.420527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6878dfe2df4a'
down_revision = '6d2b590a4a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('bills_bill_cancellation_id_fkey', type_='foreignkey')
        batch_op.drop_column('bill_cancellation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_cancellation_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('bills_bill_cancellation_id_fkey', 'bill_cancellations', ['bill_cancellation_id'], ['id'])

    # ### end Alembic commands ###
