"""Add buyer_email to invoice

Revision ID: 2a218274bf32
Revises: 392245f5a907
Create Date: 2023-04-27 09:29:41.467916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a218274bf32'
down_revision = '392245f5a907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('buyer_email')

    op.create_table('example',
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='example_pkey')
    )
    # ### end Alembic commands ###
