"""Add bill_id to billcancelation

Revision ID: 6d2b590a4a1f
Revises: e0d455362186
Create Date: 2023-05-02 09:46:38.173823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2b590a4a1f'
down_revision = 'e0d455362186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_cancellations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_cancellations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
