"""Set Invoice.buyer_id nullable

Revision ID: e0d455362186
Revises: 2a218274bf32
Create Date: 2023-04-28 09:44:41.577656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d455362186'
down_revision = '2a218274bf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
