"""Set paymentmethod nullable

Revision ID: 1d577bbc9833
Revises: 8d3a5b67978b
Create Date: 2023-05-08 14:01:42.341414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d577bbc9833'
down_revision = '8d3a5b67978b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('payment_method_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('payment_method_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
