"""Invoice.total from int to numeric, remove Request

Revision ID: 392245f5a907
Revises: b3c1c1e67bde
Create Date: 2023-04-26 11:29:10.151823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392245f5a907'
down_revision = 'b3c1c1e67bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)

    op.create_table('requests',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='requests_pkey')
    )
    # ### end Alembic commands ###
