export const termsAndConditions = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tristique elit. Duis non tortor facilisis, molestie nulla in, interdum mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi semper sit amet odio sed maximus. Mauris tempus quam vitae eleifend convallis. Phasellus elementum, neque sit amet bibendum ultrices, nisl elit tristique dui, id maximus nunc ligula quis elit. Donec nisl nisi, scelerisque nec lacus rhoncus, viverra dapibus turpis.

Nam non nulla vel ante placerat eleifend. Morbi quis ante quis purus lobortis efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque eget felis non est accumsan faucibus. Suspendisse in magna vitae magna dictum rhoncus. Praesent finibus sagittis mauris, id fermentum diam ultricies quis. Donec ac purus diam. Nulla a rhoncus lacus. Donec iaculis, orci eu sodales laoreet, sapien leo tristique magna, nec sollicitudin ex risus a leo. Vestibulum bibendum fringilla elit nec sodales. Proin gravida nibh diam, a convallis risus suscipit sit amet. Maecenas non eros consequat, finibus metus eu, fringilla nibh. Duis interdum non justo et luctus. Aliquam erat volutpat. Phasellus diam magna, ornare in efficitur quis, dictum non nibh. Sed a ultricies tellus, quis vulputate erat.

Fusce mattis, diam id venenatis ullamcorper, nunc velit pharetra nisi, at ullamcorper risus urna id magna. Duis scelerisque dui sollicitudin enim viverra suscipit. Aliquam dictum turpis turpis, eget faucibus orci mollis a. Nullam fringilla semper hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis ut arcu lectus. Nullam risus dui, fermentum eu tristique quis, tincidunt et nibh. Phasellus vitae euismod nulla. Curabitur ultricies nibh a fermentum placerat. Cras tincidunt mi turpis, eu sodales lacus pretium ac.

Sed quam felis, pharetra in elementum at, cursus in eros. Vestibulum pellentesque egestas eros vitae tempor. Curabitur sit amet lacus a massa molestie volutpat non sed neque. Nullam at nibh eu orci feugiat mollis sed suscipit eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Curabitur nulla dui, rutrum nec tempor non, vulputate ac nisi. Etiam sodales congue ornare.

Integer lacus ex, vehicula vitae congue id, pretium vel leo. Donec at mattis nisl. Duis rutrum erat nulla, eget maximus lorem tristique eu. Proin tincidunt rhoncus mauris, in viverra ipsum dictum id. Ut eleifend, ante laoreet blandit consequat, purus erat efficitur lectus, et commodo est tortor convallis magna. Nunc sit amet lectus id metus venenatis vestibulum at nec enim. Phasellus ornare metus neque, euismod mattis augue accumsan ut. `
